//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hft.Runner
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    internal static class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance created by Application
        ///   (class-level) property.
        /// </summary>
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hft.Runner.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0:O}] [INIT] Initializing TradingEngine (ALADDIN Architecture).
        /// </summary>
        internal static string EngineInit
        {
            get
            {
                return ResourceManager.GetString("EngineInit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0:O}] [ENGINE] Transitioned to STANDBY.
        /// </summary>
        internal static string EngineStandby
        {
            get
            {
                return ResourceManager.GetString("EngineStandby", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [{0:O}] [SHUTDOWN] Engine STOPPED.
        /// </summary>
        internal static string EngineStopped
        {
            get
            {
                return ResourceManager.GetString("EngineStopped", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [FIOS] Sovereign Approval: Order Qty {0:F2}.
        /// </summary>
        internal static string FiosApproval
        {
            get
            {
                return ResourceManager.GetString("FiosApproval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [FIOS] Sovereign REJECTION: {0} - {1}.
        /// </summary>
        internal static string FiosRejection
        {
            get
            {
                return ResourceManager.GetString("FiosRejection", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to === HFT MONITOR [{0:O}] ===.
        /// </summary>
        internal static string MonitorHeader
        {
            get
            {
                return ResourceManager.GetString("MonitorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State: {0} | PID: {1}.
        /// </summary>
        internal static string MonitorState
        {
            get
            {
                return ResourceManager.GetString("MonitorState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string MonitorMetric
        {
            get
            {
                return ResourceManager.GetString("MonitorMetric", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PnL: {0:F2} | Latency(p99): {1:F2}us.
        /// </summary>
        internal static string MonitorPnl
        {
            get
            {
                return ResourceManager.GetString("MonitorPnl", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Starting HFT Platform (Aladdin Architecture).
        /// </summary>
        internal static string PlatformStart
        {
            get
            {
                return ResourceManager.GetString("PlatformStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to
        ///[SHUTDOWN] Cancellation received..
        /// </summary>
        internal static string ShutdownCancelled
        {
            get
            {
                return ResourceManager.GetString("ShutdownCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shutdown complete. Exit..
        /// </summary>
        internal static string ShutdownComplete
        {
            get
            {
                return ResourceManager.GetString("ShutdownComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [OPS] Performing shadow copy to {0}....
        /// </summary>
        internal static string ShadowCopyProgress
        {
            get
            {
                return ResourceManager.GetString("ShadowCopyProgress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [OPS] Shadow copy complete. Executing isolated process....
        /// </summary>
        internal static string ShadowCopyComplete
        {
            get
            {
                return ResourceManager.GetString("ShadowCopyComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [FATAL] Engine crashed: {0}.
        /// </summary>
        internal static string FatalError
        {
            get
            {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
    }
}
